version: '3'
services:
  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  db:
