version: '3'
services:
  job-dialy:
    build:
      dockerfile: ./Dockerfile
    image: job-dialy
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mysql://root:root@host.docker.internal:3306/dialy

  db:
    image: mariadb:latest
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MARIADB_ROOT_PASSWORD: 'root'

volumes:
  db:
